# Generated by Django 5.1.1 on 2026-05-24 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_alter_category_id_alter_genre_id_alter_title_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="title",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="titles",
                to="reviews.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="title",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
